### ISSUE TITLE
saving the data

### ISSUE THREAD

**Issue by agelamin** [SICKAG/libsick_ldmrs#3]
how can I save  the data in a readable format after running the application?

**Comment by jspricke** [comment]
Hi,

please have a look at the ROS [tutorials](http://wiki.ros.org/ROS/Tutorials), esp [rostopic](http://wiki.ros.org/rostopic#rostopic_echo) and [rosbag](http://wiki.ros.org/rosbag/Commandline).
Please ask questions on ROS [answers](https://answers.ros.org).

Closing as this is a general ROS question and not a ldmrs issue.
